// src/app/components/common/footer.component.ts
import {Component, AfterViewInit, ViewChild, Input} from '@angular/core';
import ShuffleText from 'shuffle-text';


@Component({
  selector: 'app-site-footer',
  template: `
    <footer>
      <div class="pull-md-left hidden-sm-down" style="margin-left:10px;">
        <span #metaElement><i class="fa fa-code"></i> {{meta}}</span>
      </div>
      <div class="pull-md-right">
        <span class="created">All works are created by <a href="https://twitter.com/clockmaker" target="_blank">Yasunobu Ikeda</a>.</span>
        <span class="copyright"> &copy; {{_year}} <a href="http://clockmaker.jp/blog">clockmaker.jp</a></span>
      </div>
    </footer>`,
  styleUrls: [
    "./footer.scss"
  ]
})

export class FooterComponent {
  @Input() meta: string;
  _year: number;

  @ViewChild('metaElement') metaElement;

  constructor() {
    this._year = new Date().getFullYear();
  }
}

// src/components/Footer.tsx
"use client";

import styles from "./Footer.module.css";

interface FooterProps {
  meta: string;
}

export default function Footer({ meta }: FooterProps) {
  const year = new Date().getFullYear();

  return (
    <footer className={styles.footer}>
      <div className="footer-created">
        <span>
          <i className="fa fa-code"></i> {meta}
        </span>
      </div>
      <div className={styles.footerAuthor}>
        All works are created by
        <a
          href="https://twitter.com/clockmaker"
          target="_blank"
          rel="noopener noreferrer"
        >
          {" "}
          IKEDA Yasunobu
        </a>
        .
      </div>
      <div className="footer-copyright">
        &copy; {year} <a href="http://clockmaker.jp/blog">clockmaker.jp</a>
      </div>
    </footer>
  );
}
